/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/login/": {
    /**
     * @description Check the credentials and return the REST Token
     * if the credentials are valid and authenticated.
     * Calls Django Auth login method to register User ID
     * in Django session framework
     *
     * Accept the following POST parameters: username, password
     * Return the REST Framework Token Object's key.
     */
    post: operations["auth_login_create"];
  };
  "/api/v1/auth/logout/": {
    /**
     * @description Calls Django logout method and delete the Token object
     * assigned to the current User object.
     *
     * Accepts/Returns nothing.
     */
    post: operations["auth_logout_create"];
  };
  "/api/v1/auth/password/change/": {
    /**
     * @description Calls Django Auth SetPasswordForm save method.
     *
     * Accepts the following POST parameters: new_password1, new_password2
     * Returns the success/fail message.
     */
    post: operations["auth_password_change_create"];
  };
  "/api/v1/auth/password/reset/": {
    /**
     * @description Calls Django Auth PasswordResetForm save method.
     *
     * Accepts the following POST parameters: email
     * Returns the success/fail message.
     */
    post: operations["auth_password_reset_create"];
  };
  "/api/v1/auth/password/reset/confirm/": {
    /**
     * @description Password reset e-mail link is confirmed, therefore
     * this resets the user's password.
     *
     * Accepts the following POST parameters: token, uid,
     *     new_password1, new_password2
     * Returns the success/fail message.
     */
    post: operations["auth_password_reset_confirm_create"];
  };
  "/api/v1/auth/token/refresh/": {
    /**
     * @description Takes a refresh type JSON web token and returns an access type JSON web
     * token if the refresh token is valid.
     */
    post: operations["auth_token_refresh_create"];
  };
  "/api/v1/auth/token/verify/": {
    /**
     * @description Takes a token and indicates if it is valid.  This view provides no
     * information about a token's fitness for a particular use.
     */
    post: operations["auth_token_verify_create"];
  };
  "/api/v1/auth/user/": {
    /**
     * @description Reads and updates UserModel fields
     * Accepts GET, PUT, PATCH methods.
     *
     * Default accepted fields: username, first_name, last_name
     * Default display fields: pk, username, email, first_name, last_name
     * Read-only fields: pk, email
     *
     * Returns UserModel fields.
     */
    get: operations["auth_user_retrieve"];
    /**
     * @description Reads and updates UserModel fields
     * Accepts GET, PUT, PATCH methods.
     *
     * Default accepted fields: username, first_name, last_name
     * Default display fields: pk, username, email, first_name, last_name
     * Read-only fields: pk, email
     *
     * Returns UserModel fields.
     */
    put: operations["auth_user_update"];
    /**
     * @description Reads and updates UserModel fields
     * Accepts GET, PUT, PATCH methods.
     *
     * Default accepted fields: username, first_name, last_name
     * Default display fields: pk, username, email, first_name, last_name
     * Read-only fields: pk, email
     *
     * Returns UserModel fields.
     */
    patch: operations["auth_user_partial_update"];
  };
  "/api/v1/sample/": {
    get: operations["sample_list"];
    post: operations["sample_create"];
  };
  "/api/v1/sample/{id}/": {
    get: operations["sample_retrieve"];
    put: operations["sample_update"];
    delete: operations["sample_destroy"];
    patch: operations["sample_partial_update"];
  };
  "/api/v1/sample/bulk_update/": {
    put: operations["sample_bulk_update_update"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Serializer for JWT authentication. */
    JWT: {
      access_token: string;
      refresh_token: string;
      user: components["schemas"]["UserDetails"];
    };
    Login: {
      username?: string;
      /** Format: email */
      email?: string;
      password: string;
    };
    PasswordChange: {
      new_password1: string;
      new_password2: string;
    };
    /** @description Serializer for requesting a password reset e-mail. */
    PasswordReset: {
      /** Format: email */
      email: string;
    };
    /** @description Serializer for confirming a password reset attempt. */
    PasswordResetConfirm: {
      new_password1: string;
      new_password2: string;
      uid: string;
      token: string;
    };
    PatchedSample: {
      /** Format: uuid */
      id?: string;
      cookie?: number;
      /** タイトル */
      title?: string;
      /** 説明 */
      description?: string | null;
      /** 価格 */
      price?: number | null;
      /**
       * 登録日
       * Format: date-time
       */
      created_at?: string;
      /**
       * 更新日
       * Format: date-time
       */
      updated_at?: string;
    };
    /** @description User model w/o password */
    PatchedUserDetails: {
      /** ID */
      pk?: number;
      /**
       * ユーザー名
       * @description この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。
       */
      username?: string;
      /**
       * メールアドレス
       * Format: email
       */
      email?: string;
      /** 名 */
      first_name?: string;
      /** 姓 */
      last_name?: string;
    };
    RestAuthDetail: {
      detail: string;
    };
    Sample: {
      /** Format: uuid */
      id: string;
      cookie?: number;
      /** タイトル */
      title: string;
      /** 説明 */
      description?: string | null;
      /** 価格 */
      price?: number | null;
      /**
       * 登録日
       * Format: date-time
       */
      created_at: string;
      /**
       * 更新日
       * Format: date-time
       */
      updated_at: string;
    };
    TokenRefresh: {
      access: string;
      refresh: string;
    };
    TokenVerify: {
      token: string;
    };
    /** @description User model w/o password */
    UserDetails: {
      /** ID */
      pk: number;
      /**
       * ユーザー名
       * @description この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。
       */
      username: string;
      /**
       * メールアドレス
       * Format: email
       */
      email: string;
      /** 名 */
      first_name?: string;
      /** 姓 */
      last_name?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * @description Check the credentials and return the REST Token
   * if the credentials are valid and authenticated.
   * Calls Django Auth login method to register User ID
   * in Django session framework
   *
   * Accept the following POST parameters: username, password
   * Return the REST Framework Token Object's key.
   */
  auth_login_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Login"];
        "application/x-www-form-urlencoded": components["schemas"]["Login"];
        "multipart/form-data": components["schemas"]["Login"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["JWT"];
        };
      };
    };
  };
  /**
   * @description Calls Django logout method and delete the Token object
   * assigned to the current User object.
   *
   * Accepts/Returns nothing.
   */
  auth_logout_create: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  /**
   * @description Calls Django Auth SetPasswordForm save method.
   *
   * Accepts the following POST parameters: new_password1, new_password2
   * Returns the success/fail message.
   */
  auth_password_change_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordChange"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordChange"];
        "multipart/form-data": components["schemas"]["PasswordChange"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  /**
   * @description Calls Django Auth PasswordResetForm save method.
   *
   * Accepts the following POST parameters: email
   * Returns the success/fail message.
   */
  auth_password_reset_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordReset"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordReset"];
        "multipart/form-data": components["schemas"]["PasswordReset"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  /**
   * @description Password reset e-mail link is confirmed, therefore
   * this resets the user's password.
   *
   * Accepts the following POST parameters: token, uid,
   *     new_password1, new_password2
   * Returns the success/fail message.
   */
  auth_password_reset_confirm_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetConfirm"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirm"];
        "multipart/form-data": components["schemas"]["PasswordResetConfirm"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  /**
   * @description Takes a refresh type JSON web token and returns an access type JSON web
   * token if the refresh token is valid.
   */
  auth_token_refresh_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRefresh"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
        "multipart/form-data": components["schemas"]["TokenRefresh"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenRefresh"];
        };
      };
    };
  };
  /**
   * @description Takes a token and indicates if it is valid.  This view provides no
   * information about a token's fitness for a particular use.
   */
  auth_token_verify_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenVerify"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenVerify"];
        "multipart/form-data": components["schemas"]["TokenVerify"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenVerify"];
        };
      };
    };
  };
  /**
   * @description Reads and updates UserModel fields
   * Accepts GET, PUT, PATCH methods.
   *
   * Default accepted fields: username, first_name, last_name
   * Default display fields: pk, username, email, first_name, last_name
   * Read-only fields: pk, email
   *
   * Returns UserModel fields.
   */
  auth_user_retrieve: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserDetails"];
        };
      };
    };
  };
  /**
   * @description Reads and updates UserModel fields
   * Accepts GET, PUT, PATCH methods.
   *
   * Default accepted fields: username, first_name, last_name
   * Default display fields: pk, username, email, first_name, last_name
   * Read-only fields: pk, email
   *
   * Returns UserModel fields.
   */
  auth_user_update: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserDetails"];
        "application/x-www-form-urlencoded": components["schemas"]["UserDetails"];
        "multipart/form-data": components["schemas"]["UserDetails"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserDetails"];
        };
      };
    };
  };
  /**
   * @description Reads and updates UserModel fields
   * Accepts GET, PUT, PATCH methods.
   *
   * Default accepted fields: username, first_name, last_name
   * Default display fields: pk, username, email, first_name, last_name
   * Read-only fields: pk, email
   *
   * Returns UserModel fields.
   */
  auth_user_partial_update: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedUserDetails"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedUserDetails"];
        "multipart/form-data": components["schemas"]["PatchedUserDetails"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserDetails"];
        };
      };
    };
  };
  sample_list: {
    parameters: {
      query?: {
        created_at?: string;
        description?: string;
        id?: string;
        price?: number;
        price_lte?: number;
        title?: string;
        updated_at?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Sample"][];
        };
      };
    };
  };
  sample_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Sample"];
        "application/x-www-form-urlencoded": components["schemas"]["Sample"];
        "multipart/form-data": components["schemas"]["Sample"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Sample"];
        };
      };
    };
  };
  sample_retrieve: {
    parameters: {
      path: {
        /** @description A UUID string identifying this sample. */
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Sample"];
        };
      };
    };
  };
  sample_update: {
    parameters: {
      path: {
        /** @description A UUID string identifying this sample. */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Sample"];
        "application/x-www-form-urlencoded": components["schemas"]["Sample"];
        "multipart/form-data": components["schemas"]["Sample"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Sample"];
        };
      };
    };
  };
  sample_destroy: {
    parameters: {
      path: {
        /** @description A UUID string identifying this sample. */
        id: string;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  sample_partial_update: {
    parameters: {
      path: {
        /** @description A UUID string identifying this sample. */
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedSample"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedSample"];
        "multipart/form-data": components["schemas"]["PatchedSample"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Sample"];
        };
      };
    };
  };
  sample_bulk_update_update: {
    parameters: {
      query?: {
        created_at?: string;
        description?: string;
        id?: string;
        price?: number;
        price_lte?: number;
        title?: string;
        updated_at?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Sample"][];
        "application/x-www-form-urlencoded": components["schemas"]["Sample"][];
        "multipart/form-data": components["schemas"]["Sample"][];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Sample"][];
        };
      };
    };
  };
}
