# Generated by Django 3.2.25 on 2024-03-29 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='name',
            new_name='title',
        ),
    ]
