# Generated by Django 4.2.11 on 2024-04-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_rename_name_sample_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='price',
            field=models.IntegerField(default=777, verbose_name='価格'),
            preserve_default=False,
        ),
    ]
