# Generated by Django 4.2.11 on 2024-04-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_alter_sample_description_alter_sample_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='price',
            field=models.IntegerField(blank=True, error_messages={'blank': '価格フィールドは必須です。', 'null': '価格は空にできません。'}, null=True, verbose_name='価格'),
        ),
    ]
