# Generated by Django 4.2.11 on 2024-05-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_alter_sample_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='削除日'),
        ),
    ]
